name: Python application

on: 
  push: 
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install pipenv
        run: |
          pip install pipenv
          pip install pytest
      - name: Do Something with env files
        env:
          QA_ENV_FILE: ${{ secrets.TESTING }}
        run: |
          echo $QA_ENV_FILE | base64 --decode > .env
      - name: Run tests
        run: |
          pipenv install pytest
          pipenv install --dev
          pipenv run pytest
